version: '3.8'

services:
  backend:
    build:
      context: C:/Users/Lenovo/IdeaProjects/TaskManagementApplication
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
