

services:
  backend:
    build:
      context: C:/Users/Lenovo/IdeaProjects/TaskManagementApplication
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  frontend:
    build:
      context: C:/Users/Lenovo/IdeaProjects/TaskManagementApplicationAngular
    container_name: frontend-container
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
